# Generated by Django 3.0.5 on 2022-08-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_published',
        ),
        migrations.AddField(
            model_name='product',
            name='care',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='light',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
